# Allgemeine Build-Einstellungen
[build]
command = "mkdir -p bootstrap/cache storage/framework/views && composer install && php artisan view:cache && php artisan config:cache"
publish = "public"
environment = { PHP_VERSION = "8.2" } # Gewünschte PHP-Version

# Einstellungen für Redirects und Rewrites
[[redirects]]
from = "/*"
to = "/index.php"
status = 200 # Rewrites alle Anfragen an index.php (wichtig für Laravel)
